package com.pos.system.dao;
// Generated Nov 30, 2016 5:14:00 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * TblTitle generated by hbm2java
 */
public class TblTitle implements java.io.Serializable {

	private Integer intId;
	private String strTitle;
	private Set<TblEmployee> tblEmployees = new HashSet<TblEmployee>(0);

	public TblTitle() {
	}

	public TblTitle(String strTitle) {
		this.strTitle = strTitle;
	}

	public TblTitle(String strTitle, Set<TblEmployee> tblEmployees) {
		this.strTitle = strTitle;
		this.tblEmployees = tblEmployees;
	}

	public Integer getIntId() {
		return this.intId;
	}

	public void setIntId(Integer intId) {
		this.intId = intId;
	}

	public String getStrTitle() {
		return this.strTitle;
	}

	public void setStrTitle(String strTitle) {
		this.strTitle = strTitle;
	}

	public Set<TblEmployee> getTblEmployees() {
		return this.tblEmployees;
	}

	public void setTblEmployees(Set<TblEmployee> tblEmployees) {
		this.tblEmployees = tblEmployees;
	}

}
