package com.pos.system.dao;
// Generated Nov 30, 2016 5:14:00 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * TblVat generated by hbm2java
 */
public class TblVat implements java.io.Serializable {

	private Integer intId;
	private float fltVt;
	private Set<TblProductGroup> tblProductGroup = new HashSet<TblProductGroup>(0);

	public TblVat() {
	}

	public TblVat(float fltVt) {
		this.fltVt = fltVt;
	}

	public TblVat(float fltVt, Set<TblProductGroup> tblProductGroups) {
		this.fltVt = fltVt;
		this.tblProductGroup = tblProductGroups;
	}

	public Integer getIntId() {
		return this.intId;
	}

	public void setIntId(Integer intId) {
		this.intId = intId;
	}

	public float getFltVt() {
		return this.fltVt;
	}

	public void setFltVt(float fltVt) {
		this.fltVt = fltVt;
	}

	public Set<TblProductGroup> getTblProductGroup() {
		return this.tblProductGroup;
	}

	public void setTblProductGroup(Set<TblProductGroup> tblProductGroups) {
		this.tblProductGroup = tblProductGroups;
	}

}
