package com.pos.system.model;
// Generated Nov 30, 2016 5:14:00 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblReceiptHead generated by hbm2java
 */
public class TblReceiptHead implements java.io.Serializable {

	private Integer intId;
	private TblEmployee tblEmployee;
	private int intReceiptNumber;
	private Date datTimestamp;
	private float fltTotal;
	private Set<TblReceiptDetails> tblReceiptDetailses = new HashSet<TblReceiptDetails>(0);

	public TblReceiptHead() {
	}

	public TblReceiptHead(TblEmployee tblEmployee, int intReceiptNumber, Date datTimestamp, float fltTotal) {
		this.tblEmployee = tblEmployee;
		this.intReceiptNumber = intReceiptNumber;
		this.datTimestamp = datTimestamp;
		this.fltTotal = fltTotal;
	}

	public TblReceiptHead(TblEmployee tblEmployee, int intReceiptNumber, Date datTimestamp, float fltTotal,
			Set<TblReceiptDetails> tblReceiptDetailses) {
		this.tblEmployee = tblEmployee;
		this.intReceiptNumber = intReceiptNumber;
		this.datTimestamp = datTimestamp;
		this.fltTotal = fltTotal;
		this.tblReceiptDetailses = tblReceiptDetailses;
	}

	public Integer getIntId() {
		return this.intId;
	}

	public void setIntId(Integer intId) {
		this.intId = intId;
	}

	public TblEmployee getTblEmployee() {
		return this.tblEmployee;
	}

	public void setTblEmployee(TblEmployee tblEmployee) {
		this.tblEmployee = tblEmployee;
	}

	public int getIntReceiptNumber() {
		return this.intReceiptNumber;
	}

	public void setIntReceiptNumber(int intReceiptNumber) {
		this.intReceiptNumber = intReceiptNumber;
	}

	public Date getDatTimestamp() {
		return this.datTimestamp;
	}

	public void setDatTimestamp(Date datTimestamp) {
		this.datTimestamp = datTimestamp;
	}

	public float getFltTotal() {
		return this.fltTotal;
	}

	public void setFltTotal(float fltTotal) {
		this.fltTotal = fltTotal;
	}

	public Set<TblReceiptDetails> getTblReceiptDetailses() {
		return this.tblReceiptDetailses;
	}

	public void setTblReceiptDetailses(Set<TblReceiptDetails> tblReceiptDetailses) {
		this.tblReceiptDetailses = tblReceiptDetailses;
	}

}
