package com.pos.system.model;
// Generated Nov 30, 2016 5:14:00 PM by Hibernate Tools 5.2.0.Beta1

/**
 * TblReceiptDetails generated by hbm2java
 */
public class TblReceiptDetails implements java.io.Serializable {

	private Integer intId;
	private TblReceiptHead tblReceiptHead;
	private int intProductGroupId;
	private String strName;
	private float fltProfitMargin;
	private float fltVat;
	private float fltSellingPrice;

	public TblReceiptDetails() {
	}

	public TblReceiptDetails(TblReceiptHead tblReceiptHead, int intProductGroupId, String strName,
			float fltProfitMargin, float fltVat, float fltSellingPrice) {
		this.tblReceiptHead = tblReceiptHead;
		this.intProductGroupId = intProductGroupId;
		this.strName = strName;
		this.fltProfitMargin = fltProfitMargin;
		this.fltVat = fltVat;
		this.fltSellingPrice = fltSellingPrice;
	}

	public Integer getIntId() {
		return this.intId;
	}

	public void setIntId(Integer intId) {
		this.intId = intId;
	}

	public TblReceiptHead getTblReceiptHead() {
		return this.tblReceiptHead;
	}

	public void setTblReceiptHead(TblReceiptHead tblReceiptHead) {
		this.tblReceiptHead = tblReceiptHead;
	}

	public int getIntProductGroupId() {
		return this.intProductGroupId;
	}

	public void setIntProductGroupId(int intProductGroupId) {
		this.intProductGroupId = intProductGroupId;
	}

	public String getStrName() {
		return this.strName;
	}

	public void setStrName(String strName) {
		this.strName = strName;
	}

	public float getFltProfitMargin() {
		return this.fltProfitMargin;
	}

	public void setFltProfitMargin(float fltProfitMargin) {
		this.fltProfitMargin = fltProfitMargin;
	}

	public float getFltVat() {
		return this.fltVat;
	}

	public void setFltVat(float fltVat) {
		this.fltVat = fltVat;
	}

	public float getFltSellingPrice() {
		return this.fltSellingPrice;
	}

	public void setFltSellingPrice(float fltSellingPrice) {
		this.fltSellingPrice = fltSellingPrice;
	}

}
